# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
- none
pr:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# name: test_Schedule schedules: 
# - cron: '*/30 * * * *' 
#   displayName: Every 30 mins 
#   branches: 
#   include: - devops-schedule-test 
#  always: 'true' 
# trigger: none 
# pr: none

schedules:
- cron: '*/1 * * * *'  
  displayName: Every 1 mins 
  branches:
    include:
    - Feature
  always: true
  